# Generated by Django 3.0 on 2021-01-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='UserBlog',
        ),
    ]
