# Generated by Django 3.0 on 2021-01-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210101_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=100)),
                ('postname', models.TextField(blank=True)),
                ('vac', models.IntegerField(blank=True)),
                ('qualifiction', models.CharField(blank=True, max_length=50)),
                ('lastdate', models.DateTimeField(auto_now_add=True)),
                ('jobcat', models.CharField(blank=True, max_length=100)),
                ('jobloc', models.CharField(blank=True, max_length=100)),
                ('jobdes', models.TextField(blank=True)),
                ('salary', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('agelimit', models.CharField(blank=True, max_length=100)),
                ('appfee', models.TextField(blank=True)),
                ('impdate', models.TextField(blank=True)),
                ('applyproc', models.TextField(blank=True)),
                ('postedon', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-postedon'],
            },
        ),
    ]
