# Generated by Django 3.0 on 2021-01-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lastdate',
            field=models.DateTimeField(),
        ),
    ]
