# Generated by Django 3.0 on 2021-01-01 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210101_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
